### ISSUE TITLE
gate_functions.lua:406: attempt to index a nil value

### ISSUE THREAD

**Issue by Bastrabun** [minetest-mods/castle_gates#17] opened 2021-09-14 18:06 UTC
Not sure what was attempted by the user.

```
2021-09-12 19:46:47: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod '' in callback environment_Step(): ...e/mtlive1/.minetest/mods/castle_gates/gate_functions.lua:406: attempt to index a nil value
2021-09-12 19:46:47: ERROR[Main]: stack traceback:
2021-09-12 19:46:47: ERROR[Main]: 	...e/mtlive1/.minetest/mods/castle_gates/gate_functions.lua:406: in function 'func'
2021-09-12 19:46:47: ERROR[Main]: 	...ive1/5.4.1/Minetest_live/bin/../builtin/common/after.lua:26: in function 'func'
2021-09-12 19:46:47: ERROR[Main]: 	...inetest_live/bin/../builtin/profiler/instrumentation.lua:106: in function <...inetest_live/bin/../builtin/profiler/instrumentation.lua:100>
2021-09-12 19:46:47: ERROR[Main]: 	...ve1/5.4.1/Minetest_live/bin/../builtin/game/register.lua:422: in function <...ve1/5.4.1/Minetest_live/bin/../builtin/game/register.lua:406>
2021-09-12 19:46:47: ERROR[Main]: stack traceback: corrupted double-linked list
```

For my reference 897

**Comment by Bastrabun** [comment] 2022-04-07 18:58
In issue #15 you kindly allowed

> EDIT: Feel free to @ me when you find such errors if nobody seems to be active.

I feel like this is the case here again, so I do summon thee, @SmallJoker 

Thank you very much

**Comment by SmallJoker** [comment] 2022-04-07 19:29
@Bastrabun `gate_functions.lua:406` does not point to any relevant code. Please provide a stack backtrace using an unmodified castle_gates version, or provide the failing line contents in case you absolutely need a modification in this file.

**Comment by Bastrabun** [comment] 2022-04-07 19:50
This is the affected line: https://github.com/minetest-mods/castle_gates/blob/master/gate_functions.lua#L402 in fc78d92

which reads 

castle_gates.trigger_gate(door.all[1].pos, door.all[1].node,

**Comment by SmallJoker** [comment] 2022-04-08 17:56
Do you know of any reproduction steps? This seems to be related to hinges only, but I cannot figure out why `door.all` would be an empty table.

**Comment by Bastrabun** [comment] 2022-04-08 19:03
Unfortunately not. I did not find the user who did it and I wasn't able to reproduce the crash. Also there were no "uncommon" constructions involving hinges to be found.

**Comment by SmallJoker** [comment] 2022-04-08 19:31
I suppose this would be the easiest way to find the culprit:

```Lua
minetest.after(1, function(player_name)
	if not door.all[1] then
		minetest.log("warning", "HINGE ERROR WITH NODE " .. dump(node) .. ": " .. dump(door.all)
		return
	end
	-- Get current player ObjectRef (nil when gone)
	castle_gates.trigger_gate(door.all[1].pos, door.all[1].node,
		minetest.get_player_by_name(player_name))
end, player:get_player_name())
```

**Comment by Bastrabun** [comment] 2022-04-08 19:37
Will add and then call a bug bounty on castle gate hinge crashes :D

**Comment by S-S-X** [comment] 2023-01-06 17:15
Same thing just crashed another server, tried to ask for steps to reproduce but not sure if I get anything.
Attempt to index nil @ `castle_gates.trigger_gate(door.all[1].pos, door.all[1].node,` (gate_functions.lua:441).

**Comment by S-S-X** [comment] 2023-01-06 17:35
> seems like using an already  moving castle_gates:steel_portcullis_bars caused this one.

Didn't try and didn't read code that carefully but makes sense if it causes "double trigger" for trigger_gate function and leaves `door.all` empty (which also seems very much possible).

**Comment by FeXoR-o-Illuria** [comment] 2023-02-21 21:26
Yes, using (right-clicking/placing) a gate node while the gate is already moving can trigger the crash.
Rapidly clicking a gate segment that has multiple voxels to move triggers it reliably.

**Comment by Niklp09** [comment] 2023-04-29 16:55
@Bastrabun should be fixed now

**Comment by S-S-X** [comment] 2023-04-29 18:29
> @Bastrabun should be fixed now

I guess this almost sure also fixes case where gate is activated rapidly multiple times presumably caused by before `core.after(1, xyz)` had chance to actually run resulting in multiple consecutive jobs for same pos.

I guess multiple jobs can still be queued? But it just wont finish those anymore.

I mean issue that was temporarily fixed on pandorabox by switching to https://github.com/S-S-X/castle_gates/commit/818a204b9f38048b5099c45b23c495f3cb3efc29 because it was already more like public server restart button than rare bug crashing server.

**Comment by Bastrabun** [comment] 2023-05-01 22:19
Do you have a surefire repro so I could test with and without the fix?

**Comment by Niklp09** [comment] 2023-10-24 06:57
Fixed in https://github.com/minetest-mods/castle_gates/commit/c4316a082159d6a4977faaab1bf2cb38d854c97d (cannot reproduced anymore)

**Closed by Niklp09** 2023-10-24 06:57 UTC
